import {createAsyncThunk, createSlice, PayloadAction} from '@reduxjs/toolkit'
import {getToken,setToken} from "../../utilities/auth";
import {login, LoginForm} from "../../apis/userManagment";
import {AppState} from "../../store";

export interface UserState {
    token: string | undefined
    role: string
    username: string
    userId: string
}

const initialState: UserState = {
    token: getToken(),
    role: '',
    username: '',
    userId: ''
}

export const loginAsync = createAsyncThunk(
    'user/login',
    async (userInfo: LoginForm) => {
        // const response = await login(userInfo)
        // return response.data
        await setTimeout(()=>{},1000)
        return {
            token: 'userToken',
            role: 'commercial',
            username: 'commercial',
            userId: '0001'
        }
    }
)

export const userSlice = createSlice({
    name: 'user',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setUsername: (state,action: PayloadAction<string>) => {
            state.username = action.payload
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(loginAsync.fulfilled, (state, action) => {
                if (action.payload !== null) {
                    const { token, role, username, userId } = action.payload;
                    state.token = token;
                    state.role = role;
                    state.username = username;
                    state.userId = userId;
                    setToken(action.payload.token)
                }
            })
    },
})

export const {setUsername} = userSlice.actions

export const selectToken = (state: AppState) => state.user.token
export const selectRole = (state: AppState) => state.user.role
export const selectUsername = (state: AppState) => state.user.username
export const selectUserid = (state: AppState) => state.user.userId



export default userSlice.reducer
